import { readFile, mkdir, mkdtemp, writeFile, rename, rm, readdir, lstat } from 'node:fs/promises'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { subclasses } from '../../content/catalog/subclasses.js'
import { abilities } from '../../content/catalog/abilities.js'
import { aspects } from '../../content/catalog/aspects.js'
import { facets } from '../../content/catalog/facets.js'
import { fragments } from '../../content/catalog/fragments.js'
import { activitiesV2 as activities } from '../../content/catalog/activities.js'
import { assertRepository, buildSnapshot } from './index.js'

export async function loadValidationContext(catalogDir = fileURLToPath(new URL('../../web/public/data/', import.meta.url))) {
  const entries = [['equipment', 'manifest-equipment-rich', 'items'], ['manifestAbilities', 'manifest-abilities', 'items'], ['mods', 'manifest-mods', 'items'], ['artifacts', 'manifest-artifact', 'items'], ['plugSets', 'manifest-plugsets', 'sets']]
  const payloads = await Promise.all(entries.map(async ([key, file, list]) => {
    const data = JSON.parse(await readFile(join(catalogDir, `${file}.json`), 'utf8'))
    if (!data.manifestVersion || !Array.isArray(data[list]) || !data[list].length || data.count !== data[list].length) throw new Error(`校验目录缺失或损坏：${file}`)
    return { key, items: data[list], version: data.manifestVersion }
  }))
  if (new Set(payloads.map(p => p.version)).size !== 1) throw new Error('校验目录版本不一致，终止本次同步')
  return { subclasses, abilities, aspects, facets, fragments, activities, ...Object.fromEntries(payloads.map(p => [p.key, p.items])), manifestVersion: payloads[0].version }
}

export async function fetchIssues(repository, { token, fetchImpl = fetch, maxPages = 1000 } = {}) {
  assertRepository(repository)
  const headers = { Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'd2hub-community-builds' }
  if (token) headers.Authorization = `Bearer ${token}`
  const issues = []
  for (let page = 1; page <= maxPages; page++) {
    const response = await fetchImpl(`https://api.github.com/repos/${repository}/issues?state=all&sort=created&direction=asc&per_page=100&page=${page}`, { headers, signal: AbortSignal.timeout(30000), redirect: 'error' })
    if (!response.ok) throw new Error(`GitHub Issue 第 ${page} 页读取失败（HTTP ${response.status}），未发布新快照`)
    const rows = await response.json()
    if (!Array.isArray(rows)) throw new Error('GitHub 返回了非列表响应')
    issues.push(...rows)
    // Follow pagination metadata rather than assuming a short page is the last.
    if (!/rel="next"/.test(response.headers.get('link') || '')) return issues
  }
  throw new Error('Issue 分页超过同步上限，未发布不完整快照')
}

// Only replace a directory created by this generator. Never clean an arbitrary path.
export async function publishSnapshot(snapshot, outputDir) {
  const target = resolve(outputDir), parent = dirname(target)
  await mkdir(parent, { recursive: true })
  try {
    const stat = await lstat(target)
    if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error('输出路径必须是生成目录')
    const files = await readdir(target)
    if (files.length && !files.includes('.d2hub-generated')) throw new Error('输出目录已有其他文件，拒绝覆盖')
  } catch (e) { if (e.code !== 'ENOENT') throw e }
  const staging = await mkdtemp(join(parent, '.community-staging-'))
  try {
    await writeFile(join(staging, 'community-builds.json'), JSON.stringify(snapshot) + '\n')
    await writeFile(join(staging, '.d2hub-generated'), 'Generated by d2hub. Do not store source files here.\n')
    await writeFile(join(staging, 'index.html'), '<!doctype html><meta charset="utf-8"><title>社区构筑数据</title><a href="community-builds.json">社区构筑公开快照</a>')
    await rm(target, { recursive: true, force: true })
    await rename(staging, target)
  } finally { await rm(staging, { recursive: true, force: true }) }
}

export async function syncBuilds({ repository, outputDir, fixture, token, validatorRevision = 'local', catalogDir, fetchImpl }) {
  const context = await loadValidationContext(catalogDir)
  const issues = fixture ? JSON.parse(await readFile(fixture, 'utf8')) : await fetchIssues(repository, { token, fetchImpl })
  const snapshot = buildSnapshot(issues, context, { repository, validatorRevision })
  await publishSnapshot(snapshot, outputDir)
  return snapshot
}
