import { readFile } from 'node:fs/promises'
// Generated by audit:catalog; do not substitute editorial counts for coverage.
const report = JSON.parse(await readFile(new URL('../data/catalog/manifest-coverage.json', import.meta.url), 'utf8'))
console.log(JSON.stringify(report, null, 2))
if (report.status !== 'passed') process.exitCode = 1
